import Head from 'next/head'
import { useState } from 'react'
import {Image} from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [websiteURL, setWebsiteURL] = useState('')
  const [imageURL, setImageURL] = useState('')

  const submitWebsiteURL = async() => {
    const info = await fetch('/api/get-screenshot-image', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        url : websiteURL
      })
    }).then(res => res.json())

    console.log(info)
    setImageURL(info.data)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Next S3 App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image key={imageURL} src={imageURL} height="720" width="1280"  />

      <div className={styles.inputArea} >
        <input
          type="text"
          placeholder="Enter URL"
          value={websiteURL}
          onChange={e=> setWebsiteURL(e.target.value)}
        />
        <button onClick={submitWebsiteURL}>Submit URL</button>
      </div>

    </div>
  )
}
